services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    restart: always
    ports:
      - '4566:4566'
      - '4571:4571'
    environment:
      - SERVICES=kinesis